name: GOATCR7-Bot-V1
services:
  - name: GOATCR7-Bot-V1-service
    type: web
    ports:
      - 5000
    routes:
      - path: "/"
    build:
      type: docker
      dockerfile: ./Dockerfile
    regions:
      - fra
      - sin
      
