FROM node:lts-buster
RUN git clone https://github.com/botwastapp/GOATCR7-Bot-V1/root/botwastapp 
WORKDIR /root/botwastapp
RUN npm install && npm install -g pm2 || yarn install --network-concurrency 1
COPY . .
EXPOSE 9090
CMD ["npm", "start"]
